# Generated by Django 4.2.3 on 2023-07-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_month',
            field=models.CharField(default='Jan', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.IntegerField(),
        ),
    ]
